name: WatermarkMyImages CI

on:
  push:

permissions:
  contents: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Validate Composer
      run: |
        composer validate --strict

    - name: Install Composer
      run: |
        composer install --prefer-dist --no-progress

    - name: Run Linting
      run: |
        composer run lint

    - name: Run Testing
      run: |
        composer run test
